// Gemini AI API utilities

// Helper to get the API key from environment variables
const getGeminiApiKey = () => {
  return import.meta.env.VITE_GEMINI_API_KEY || "AIzaSyD0j-gp-B9_QH9HUD3IXtxZWSMZr7WVLr8";
};

// Placeholder for Gemini AI text generation
export const generateAIResponse = async (prompt: string) => {
  const apiKey = getGeminiApiKey();
  console.log(`Generating AI response for: "${prompt}" using API key: ${apiKey}`);
  
  // In a real app, you would use the Gemini API with actual API call
  // For now returning a placeholder response
  return `AI response to: ${prompt}\n\nThis is a placeholder response. In the actual implementation, this would be generated by Google's Gemini AI API based on the provided prompt.`;
};

// Placeholder for AI-generated questions
export const generateQuestions = async (topic: string, difficulty: string, count: number) => {
  // In a real app, you would use the Gemini API to generate questions
  console.log(`Generating ${count} ${difficulty} questions about ${topic}`);
  
  const questions = Array(count).fill(null).map((_, index) => ({
    id: `q_${Math.random().toString(36).substr(2, 9)}`,
    question: `Sample ${difficulty} question #${index + 1} about ${topic}?`,
    options: [
      `Answer option A for question #${index + 1}`,
      `Answer option B for question #${index + 1}`,
      `Answer option C for question #${index + 1}`,
      `Answer option D for question #${index + 1}`
    ],
    correctAnswer: Math.floor(Math.random() * 4)
  }));
  
  return questions;
};

// Placeholder for AI-generated feedback
export const generateFeedback = async (
  studentName: string,
  subject: string,
  performance: number,
  strengths: string[],
  weaknesses: string[]
) => {
  // In a real app, you would use the Gemini API to generate personalized feedback
  console.log(`Generating feedback for ${studentName} in ${subject}`);
  
  return `
    Dear ${studentName},
    
    I've reviewed your recent performance in ${subject} (${performance}%).
    
    Strengths:
    ${strengths.map(s => `- ${s}`).join('\n')}
    
    Areas to improve:
    ${weaknesses.map(w => `- ${w}`).join('\n')}
    
    Keep up the good work!
    
    (This is a placeholder. The actual feedback would be generated by Gemini AI)
  `;
};

// Placeholder for AI learning path recommendations
export const recommendLearningPath = async (
  studentName: string,
  interests: string[],
  currentSkills: string[],
  goals: string[]
) => {
  // In a real app, you would use the Gemini API to generate learning recommendations
  console.log(`Generating learning path for ${studentName}`);
  
  return {
    name: `Custom learning path for ${studentName}`,
    description: `Based on your interests in ${interests.join(', ')} and your goals related to ${goals.join(', ')}`,
    steps: [
      {
        title: "Foundation Building",
        resources: [
          { type: "course", name: "Introduction to Subject", duration: "2 weeks" },
          { type: "book", name: "Subject Fundamentals", pages: 120 }
        ]
      },
      {
        title: "Skill Development",
        resources: [
          { type: "project", name: "Hands-on Project", duration: "3 weeks" },
          { type: "workshop", name: "Interactive Workshop", duration: "1 day" }
        ]
      },
      {
        title: "Advanced Learning",
        resources: [
          { type: "course", name: "Advanced Techniques", duration: "4 weeks" },
          { type: "mentorship", name: "Expert Mentorship Session", duration: "1 month" }
        ]
      }
    ]
  };
};

// NEW: AI Mentor Bot
export const aiMentorChat = async (
  studentName: string,
  studentGrade: string,
  conversation: { role: 'user' | 'assistant', content: string }[],
  subject?: string
) => {
  // In a real app, you would use the Gemini API for an AI mentor chatbot
  console.log(`AI Mentor responding to ${studentName} (Grade ${studentGrade})`);
  
  // Find the last user message without using findLast
  let lastUserMessage = '';
  for (let i = conversation.length - 1; i >= 0; i--) {
    if (conversation[i].role === 'user') {
      lastUserMessage = conversation[i].content;
      break;
    }
  }
  
  let response = '';
  if (subject) {
    response = `I'm your AI Mentor for ${subject}. In response to: "${lastUserMessage}"\n\nHere's how I can help you understand this concept better...`;
  } else {
    response = `I'm your AI Mentor. In response to: "${lastUserMessage}"\n\nLet me guide you through this...`;
  }
  
  return {
    response,
    suggestedQuestions: [
      "Can you explain this in simpler terms?",
      "How does this apply to real life?",
      "Can you give me a practice problem?"
    ],
    relatedResources: [
      { type: "video", title: "Visual Explanation", url: "#" },
      { type: "article", title: "In-depth Guide", url: "#" }
    ]
  };
};

// NEW: AI Doubt Solving Bot
export const solveDoubt = async (
  subject: string,
  question: string,
  studentGrade: string,
  attachmentUrls?: string[]
) => {
  // In a real app, you would use the Gemini API for doubt solving
  console.log(`Solving ${subject} doubt for Grade ${studentGrade} student`);
  
  return {
    explanation: `Here's the solution to your question about ${subject}: "${question}"\n\nThe approach to solve this is...\n\n(This would be generated by Gemini AI)`,
    steps: [
      "First, understand the problem statement.",
      "Identify the key concepts involved.",
      "Apply the relevant formula or method.",
      "Solve step by step."
    ],
    visualAid: attachmentUrls ? "I've analyzed your attachment and..." : undefined,
    additionalResources: [
      { type: "video", title: "Watch this tutorial", url: "#" },
      { type: "practice", title: "Try similar problems", url: "#" }
    ]
  };
};

// NEW: Student Progress Analysis
export const analyzeStudentProgress = async (
  studentId: string,
  performanceData: {
    subject: string;
    scores: number[];
    activities: { type: string; completion: number }[];
    attendance: number;
  }[]
) => {
  // In a real app, you would use the Gemini API to analyze student progress
  console.log(`Analyzing progress for student ${studentId}`);
  
  const overallScore = performanceData.reduce((total, subject) => 
    total + (subject.scores.reduce((sum, score) => sum + score, 0) / subject.scores.length), 0) / performanceData.length;
  
  return {
    summary: `Overall performance is ${overallScore.toFixed(1)}% (${overallScore > 75 ? 'Good' : overallScore > 60 ? 'Average' : 'Needs improvement'})`,
    strengths: [
      `Strong performance in ${performanceData.sort((a, b) => 
        (b.scores.reduce((sum, score) => sum + score, 0) / b.scores.length) - 
        (a.scores.reduce((sum, score) => sum + score, 0) / a.scores.length)
      )[0]?.subject || 'Mathematics'}`,
      "Regular attendance and participation"
    ],
    areasOfImprovement: [
      `Needs more focus on ${performanceData.sort((a, b) => 
        (a.scores.reduce((sum, score) => sum + score, 0) / a.scores.length) - 
        (b.scores.reduce((sum, score) => sum + score, 0) / b.scores.length)
      )[0]?.subject || 'Science'}`,
      "More consistent homework submission"
    ],
    recommendations: [
      "Schedule weekly review sessions",
      "Practice with more interactive exercises",
      "Consider peer learning groups for challenging topics"
    ],
    predictedTrend: "If current study patterns continue, we expect improvement in the next 2 months.",
    suggestedResources: [
      { type: "study_guide", title: "Focused Study Plan", url: "#" },
      { type: "practice_set", title: "Custom Practice Problems", url: "#" }
    ]
  };
};

// NEW: AI Content Generation for Teachers
export const generateTeacherContent = async (
  subject: string,
  topic: string,
  gradeLevel: string,
  contentType: 'lesson_plan' | 'worksheet' | 'presentation' | 'quiz' | 'activity'
) => {
  // In a real app, you would use the Gemini API to generate teacher content
  console.log(`Generating ${contentType} for ${subject}: ${topic} (Grade ${gradeLevel})`);
  
  const contentMap = {
    lesson_plan: {
      title: `Lesson Plan: ${topic}`,
      objectives: [
        "Students will understand key concepts of the topic",
        "Students will be able to apply learned concepts to solve problems",
        "Students will develop critical thinking skills related to the subject"
      ],
      materials: ["Textbook", "Handouts", "Interactive tools"],
      timeline: [
        { activity: "Introduction", duration: "10 minutes", description: "Brief overview of the topic" },
        { activity: "Main Lesson", duration: "25 minutes", description: "Detailed explanation with examples" },
        { activity: "Practice", duration: "15 minutes", description: "Guided practice problems" },
        { activity: "Assessment", duration: "10 minutes", description: "Quick quiz to check understanding" }
      ],
      assessment: "Short quiz and observation of student participation",
      differentiation: "Additional support for struggling students, challenge problems for advanced students",
      homework: "Complete practice worksheet with 5 problems"
    },
    worksheet: {
      title: `${topic} Worksheet`,
      instructions: "Complete the following problems related to the topic.",
      problems: Array(5).fill(null).map((_, i) => ({
        question: `Problem ${i+1}: Sample problem about ${topic}`,
        difficulty: i < 2 ? "easy" : i < 4 ? "medium" : "challenging"
      })),
      rubric: "Each question is worth 2 points. Show all your work."
    },
    presentation: {
      title: `${topic} - Interactive Presentation`,
      slides: [
        { title: "Introduction", content: "Overview of key concepts", notes: "Engage students with opening question" },
        { title: "Main Concepts", content: "Detailed explanation of core ideas", notes: "Use visual aids here" },
        { title: "Examples", content: "Worked examples demonstrating application", notes: "Have students attempt before showing solution" },
        { title: "Interactive Activity", content: "Group work on concept application", notes: "Monitor groups and provide guidance" },
        { title: "Summary", content: "Recap of key points", notes: "Check for understanding with quick questions" }
      ]
    },
    quiz: {
      title: `${topic} Quiz`,
      timeLimit: "20 minutes",
      questions: Array(10).fill(null).map((_, i) => ({
        id: i+1,
        question: `Sample question ${i+1} about ${topic}?`,
        type: i < 7 ? "multiple_choice" : "short_answer",
        options: i < 7 ? ["Option A", "Option B", "Option C", "Option D"] : undefined,
        answer: i < 7 ? "Option B" : "Sample answer text."
      }))
    },
    activity: {
      title: `${topic} Interactive Activity`,
      objective: "Engage students in practical application of the topic",
      groupSize: "3-4 students",
      materials: ["Worksheets", "Manipulatives", "Reference materials"],
      procedure: [
        "Divide students into groups",
        "Distribute materials to each group",
        "Explain the activity objectives",
        "Allow 20 minutes for group work",
        "Have groups present their findings"
      ],
      assessment: "Group presentation and individual reflection"
    }
  };
  
  return contentMap[contentType];
};

// NEW: Automated Assignment Grading
export const gradeAssignment = async (
  assignmentType: string,
  studentSubmission: string,
  rubric: { criteria: string, weight: number }[],
  gradeLevel: string,
  subject: string
) => {
  // In a real app, you would use the Gemini API for automated grading
  console.log(`Grading ${subject} ${assignmentType} for grade ${gradeLevel}`);
  
  const score = Math.floor(Math.random() * 41) + 60; // Random score between 60-100
  
  return {
    overallScore: score,
    feedback: `This ${assignmentType} demonstrates ${score > 90 ? 'excellent' : score > 80 ? 'good' : score > 70 ? 'satisfactory' : 'basic'} understanding of the subject matter.`,
    detailedRubricScores: rubric.map(criterion => ({
      criteria: criterion.criteria,
      score: Math.floor(Math.random() * (criterion.weight + 1)),
      maxScore: criterion.weight,
      feedback: `Sample feedback for ${criterion.criteria}`
    })),
    strengths: [
      "Clear understanding of core concepts",
      "Good organization of ideas"
    ],
    areasForImprovement: [
      "Could provide more supporting evidence",
      "Consider expanding on the analysis section"
    ],
    suggestedResources: [
      { type: "article", title: "Guide to Improving Analysis", url: "#" },
      { type: "practice", title: "Additional Practice Problems", url: "#" }
    ]
  };
};

// NEW: Feedback and Analysis Bot
export const generateDetailedFeedback = async (
  studentName: string,
  subject: string,
  assignmentType: string,
  performance: {
    score: number,
    details: { section: string, score: number, maxScore: number }[]
  },
  previousPerformance?: number[]
) => {
  // In a real app, you would use the Gemini API for detailed feedback
  console.log(`Generating detailed feedback for ${studentName}'s ${subject} ${assignmentType}`);
  
  const avgPrevPerformance = previousPerformance ? 
    previousPerformance.reduce((sum, score) => sum + score, 0) / previousPerformance.length : null;
  
  const improvementText = avgPrevPerformance ? 
    (performance.score > avgPrevPerformance ? 
      `This is an improvement of ${(performance.score - avgPrevPerformance).toFixed(1)}% compared to your average.` : 
      `This is ${(avgPrevPerformance - performance.score).toFixed(1)}% below your average performance.`) : '';
  
  return {
    personalizedGreeting: `Hello ${studentName},`,
    overallFeedback: `Your overall performance on this ${assignmentType} was ${performance.score}%. ${improvementText}`,
    detailedAnalysis: performance.details.map(detail => ({
      section: detail.section,
      performance: `${detail.score}/${detail.maxScore}`,
      feedback: `In the ${detail.section} section, you ${detail.score > (detail.maxScore * 0.8) ? 'demonstrated strong understanding' : detail.score > (detail.maxScore * 0.6) ? 'showed good effort but missed some key points' : 'need to review core concepts'}. ${Math.random() > 0.5 ? 'Consider reviewing chapter materials on this topic.' : 'Try additional practice problems to strengthen your skills here.'}`
    })),
    strengthsAndWeaknesses: {
      strengths: [
        `Good grasp of ${performance.details.sort((a, b) => (b.score / b.maxScore) - (a.score / a.maxScore))[0]?.section || 'core concepts'}`,
        "Clear presentation of ideas"
      ],
      weaknesses: [
        `Need more work on ${performance.details.sort((a, b) => (a.score / a.maxScore) - (b.score / b.maxScore))[0]?.section || 'advanced topics'}`,
        "Could improve organization and structure"
      ]
    },
    nextSteps: [
      "Review feedback for each section",
      "Complete recommended practice problems",
      "Schedule a follow-up if you have questions"
    ],
    resources: [
      { type: "video", title: "Topic Explanation", url: "#" },
      { type: "practice", title: "Practice Problems", url: "#" },
      { type: "notes", title: "Study Guide", url: "#" }
    ]
  };
};

// NEW: Verify Donation Requests
export const verifyDonationRequest = async (
  requestDetails: {
    requesterId: string;
    deviceNeeded: string;
    purpose: string;
    schoolInfo: string;
    familyBackground: string;
    previousRequests: number;
  },
  attachedDocuments: string[]
) => {
  // In a real app, you would use the Gemini API to verify donation requests
  console.log(`Verifying donation request from ${requestDetails.requesterId}`);
  
  // Simulate verification logic
  const isFamilyNeedy = requestDetails.familyBackground.toLowerCase().includes('low income') || 
                          requestDetails.familyBackground.toLowerCase().includes('financial hardship');
  const isEducationalPurpose = requestDetails.purpose.toLowerCase().includes('education') || 
                              requestDetails.purpose.toLowerCase().includes('school') ||
                              requestDetails.purpose.toLowerCase().includes('study');
  const hasManyPreviousRequests = requestDetails.previousRequests > 3;
  
  const verificationScore = (isFamilyNeedy ? 35 : 15) + 
                           (isEducationalPurpose ? 35 : 10) +
                           (hasManyPreviousRequests ? -20 : 10) +
                           (attachedDocuments.length > 1 ? 20 : 0);
  
  return {
    isVerified: verificationScore >= 60,
    verificationScore,
    confidenceLevel: verificationScore >= 80 ? 'High' : verificationScore >= 60 ? 'Medium' : 'Low',
    analysis: {
      needAssessment: isFamilyNeedy ? 'High need demonstrated' : 'Need criteria partially met',
      purposeAlignment: isEducationalPurpose ? 'Clear educational purpose' : 'Purpose needs clarification',
      requestHistory: hasManyPreviousRequests ? 'Multiple previous requests' : 'Reasonable request history',
      documentation: attachedDocuments.length > 1 ? 'Sufficient documentation provided' : 'Additional documentation may be required'
    },
    recommendation: verificationScore >= 60 
      ? `Recommend approval of ${requestDetails.deviceNeeded} for educational purposes` 
      : 'Recommend requesting additional information before proceeding',
    suggestedNextSteps: verificationScore >= 60 
      ? ['Process donation request', 'Schedule device handover'] 
      : ['Request additional documentation', 'Conduct follow-up interview', 'Reassess after additional information']
  };
};

// NEW: Virtual Lab Assistant
export const virtualLabAssistant = async (
  experimentType: string,
  experimentStep: string,
  studentQuestion: string,
  previousSteps?: { step: string, result: string }[]
) => {
  // In a real app, you would use the Gemini API for virtual lab assistance
  console.log(`Virtual lab assistant for ${experimentType} experiment, step: ${experimentStep}`);
  
  return {
    answer: `For your question about ${experimentType} experiment: "${studentQuestion}"\n\nHere's what you need to know: During the ${experimentStep} step, you should focus on...\n\n(This would be generated by Gemini AI)`,
    visualGuidance: "Visual explanation of the correct procedure",
    safetyReminders: [
      "Always wear safety goggles during this experiment",
      "Handle chemicals carefully according to instructions",
      "Report any spills immediately"
    ],
    commonMistakes: [
      "Adding reagents in incorrect order",
      "Using wrong measurements",
      "Skipping calibration step"
    ],
    nextSteps: previousSteps 
      ? "Based on your previous steps, now you should proceed to..."
      : "After completing this step, you should proceed to...",
    troubleshooting: [
      { issue: "No reaction occurring", solution: "Check reagent concentrations and try again" },
      { issue: "Unexpected color change", solution: "This may indicate contamination, restart with fresh materials" }
    ]
  };
};

// NEW: Freelance and Course Recommendations
export const recommendFreelanceAndCourses = async (
  studentSkills: string[],
  interests: string[],
  educationLevel: string,
  timeAvailability: 'low' | 'medium' | 'high'
) => {
  // In a real app, you would use the Gemini API for personalized recommendations
  console.log(`Generating freelance and course recommendations based on ${studentSkills.join(', ')} skills`);
  
  // Simulate recommendation engine
  const skillMap: {[key: string]: {freelance: any[], courses: any[]}} = {
    'programming': {
      freelance: [
        { title: "Web Development Projects", platform: "Fiverr", avgPay: "₹1000-5000", difficulty: "Medium" },
        { title: "Mobile App Bug Fixes", platform: "Upwork", avgPay: "₹2000-8000", difficulty: "Medium-High" }
      ],
      courses: [
        { title: "Full Stack Web Development", platform: "Udemy", duration: "3 months", cost: "₹500" },
        { title: "Mobile App Development with Flutter", platform: "Coursera", duration: "2 months", cost: "₹2000" }
      ]
    },
    'writing': {
      freelance: [
        { title: "Content Writing", platform: "Fiverr", avgPay: "₹500-2000", difficulty: "Low-Medium" },
        { title: "Academic Writing", platform: "Chegg", avgPay: "₹1000-3000", difficulty: "Medium" }
      ],
      courses: [
        { title: "Creative Writing Masterclass", platform: "Udemy", duration: "6 weeks", cost: "₹400" },
        { title: "SEO Content Writing", platform: "Skillshare", duration: "4 weeks", cost: "₹600" }
      ]
    },
    'design': {
      freelance: [
        { title: "Logo Design", platform: "Fiverr", avgPay: "₹1000-4000", difficulty: "Medium" },
        { title: "UI/UX Projects", platform: "Upwork", avgPay: "₹3000-10000", difficulty: "High" }
      ],
      courses: [
        { title: "Graphic Design Fundamentals", platform: "Udemy", duration: "2 months", cost: "₹700" },
        { title: "UI/UX Design Bootcamp", platform: "Coursera", duration: "3 months", cost: "₹2500" }
      ]
    },
    'teaching': {
      freelance: [
        { title: "Online Tutoring", platform: "Chegg", avgPay: "₹300-800/hour", difficulty: "Medium" },
        { title: "Course Creation", platform: "Udemy", avgPay: "Variable", difficulty: "High" }
      ],
      courses: [
        { title: "Effective Online Teaching", platform: "Coursera", duration: "4 weeks", cost: "₹1000" },
        { title: "Creating Engaging Educational Content", platform: "edX", duration: "6 weeks", cost: "₹1200" }
      ]
    },
    'data': {
      freelance: [
        { title: "Data Entry", platform: "Fiverr", avgPay: "₹500-1500", difficulty: "Low" },
        { title: "Data Analysis Projects", platform: "Upwork", avgPay: "₹3000-12000", difficulty: "High" }
      ],
      courses: [
        { title: "Data Science Fundamentals", platform: "Coursera", duration: "3 months", cost: "₹2000" },
        { title: "Python for Data Analysis", platform: "Udemy", duration: "2 months", cost: "₹600" }
      ]
    }
  };
  
  // Match skills to recommendations
  const recommendedFreelance: any[] = [];
  const recommendedCourses: any[] = [];
  
  studentSkills.forEach(skill => {
    // Find matching skill category
    for (const [category, recommendations] of Object.entries(skillMap)) {
      if (skill.toLowerCase().includes(category)) {
        // Filter freelance by time availability
        const timeAvailabilityMap: {[key: string]: number} = { 'low': 0, 'medium': 1, 'high': 2 };
        const difficultySuitability: {[key: string]: number} = { 
          'Low': 0, 'Low-Medium': 1, 'Medium': 2, 'Medium-High': 3, 'High': 4 
        };
        
        const suitableFreelance = recommendations.freelance.filter(job => 
          difficultySuitability[job.difficulty] <= timeAvailabilityMap[timeAvailability] + 2
        );
        
        recommendedFreelance.push(...suitableFreelance);
        recommendedCourses.push(...recommendations.courses);
        break;
      }
    }
  });
  
  return {
    freelanceOpportunities: recommendedFreelance.slice(0, 5).map(job => ({
      ...job,
      skillAlignment: "Based on your skills in " + studentSkills.join(", "),
      estimatedTimePerWeek: job.difficulty.includes("Low") ? "5-10 hours" : job.difficulty.includes("Medium") ? "10-15 hours" : "15-20 hours",
      requirements: "Portfolio and basic experience required"
    })),
    recommendedCourses: recommendedCourses.slice(0, 5).map(course => ({
      ...course,
      relevance: "Aligns with your interests in " + interests.filter((_, i) => i < 2).join(", "),
      completionCertificate: true,
      careerImpact: "Can enhance your freelancing prospects",
      prerequisites: course.title.includes("Fundamentals") ? "None" : "Basic knowledge required"
    })),
    platformRecommendations: [
      { name: "Fiverr", suitability: "Good for beginners", avgRating: "4.2/5" },
      { name: "Upwork", suitability: "Better for experienced freelancers", avgRating: "4.5/5" },
      { name: "Chegg", suitability: "Good for academic subjects", avgRating: "4.0/5" }
    ],
    earnings: {
      potentialMonthlyIncome: timeAvailability === 'low' ? "₹3,000 - ₹8,000" : 
                               timeAvailability === 'medium' ? "₹8,000 - ₹15,000" : 
                               "₹15,000 - ₹30,000",
      timeToFirstProject: "1-2 weeks with proper profile setup",
      growthPotential: "Income can increase by 50-100% within 6 months with consistent quality work"
    },
    gettingStartedGuide: [
      "Create profiles on recommended platforms",
      "Build a simple portfolio showcasing your skills",
      "Start with smaller projects to build reviews",
      "Take recommended courses to enhance skills",
      "Gradually increase rates as you gain experience"
    ]
  };
};
